# config.yaml

# Default location for all datasets created by this script.
location: "us-central1"

# Policy for handling location mismatches when replication is disabled.
# 'warn': Print a warning and continue (Default).
# 'fail': Print an error and stop the deployment.
on_location_mismatch: "warn"

# --- Cross-Region Replication Policy ---
replication:
  # Set to true to enable the replication feature.
  # If a dataset exists in a different region, a replica will be created in the 'location' defined above.
  # This is an asynchronous "fire-and-forget" operation.
  enabled: false # Disabled by default for safety.

# A list of environment suffixes to append to each base name.
environments:
  - "dev"
  - "prod"

# A list of standard base names for the datasets to be created.
base_names:
  - "MAD_L0"
  - "MAD_L2"
  - "MAD_ETL"
  - "MAD_DWH"
  - "MAD_INTERMEDIATE"
