# config.yaml

# Default location for all datasets created by this script.
location: "US"

# Policy for handling location mismatches when replication is disabled.
on_location_mismatch: "warn"

# --- Cross-Region Replication Policy ---
replication:
  # Set to true to enable the replication feature.
  enabled: true # Disabled by default for safety.

  # If true, the script will promote the new replica to be the new primary.
  promote_replica_to_primary: false

# A list of environment suffixes to append to each base name.
environments:
  - "dev"
  - "prod"

# A list of standard base names for the datasets to be created.
base_names:
  - "MAD_L0"
  - "MAD_L2"
  - "MAD_ETL"
  - "MAD_DWH"
  - "MAD_INTERMEDIATE"
