# config.yaml
# The GCP project is determined automatically from the execution environment.

# Default location for all datasets created by this script.
location: "US"

# Policy for handling location mismatches.
# 'warn': Print a warning and continue (Default).
# 'fail': Print an error and stop the deployment.
on_location_mismatch: "warn"

# A list of environment suffixes to append to each base name.
environments:
  - "dev"
  - "prod"

# A list of standard base names for the datasets to be created.
# This provides a consistent structure for all projects.
base_names:
  - "MAD_L0"
  - "MAD_L2"
  - "MAD_ETL"
  - "MAD_DWH"
  - "MAD_INTERMEDIATE"
