# config.yaml
# The GCP project is determined automatically from the execution environment.

# Default location for all datasets created by this script.
# You can override this on a per-dataset basis if needed.
location: "us-central1"

# A list of environment suffixes to append to each base name.
# For each base_name, a dataset will be created for each environment.
# e.g., 'sales' + 'dev' -> 'sales_dev'
environments:
  - "DEV"
  - "PROD"

# A list of base names for the datasets to be created.
base_names:
  - "MAD_L0"
  - "MAD_L1"
  - "MAD_L1"

# Optional: You can also define datasets with specific locations if you
# need to override the default location.
# specific_datasets:
#   - name: "data_science"
#     location: "EU"
#     environments: ["dev"] # You can even override environments
